name: app_package_publisher_github
description: Publish your app to github.
version: 0.2.3
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_publisher: ^0.2.3
  dio: ^4.0.4
  parse_app_package: ^0.2.3
