name: app_package_publisher_playstore
description: Publish your app to playstore.
version: 0.2.0
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_publisher: ^0.1.5
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  http: any
  parse_app_package: ^0.1.3
