name: app_package_maker_appimage
description: Create a appImage package for your app.
version: 0.2.3
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.2.3
  path: ^1.8.1
