name: app_package_maker_zip
description: Create a zip package for your app.
version: 0.2.3
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.2.3
  archive: ^3.1.5
